# Generated by Django 5.0.7 on 2025-06-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("detail", models.TextField()),
                ("image", models.ImageField(upload_to="product_images/")),
                ("approx_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("carat", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pendants", "Pendants"),
                            ("necklaces", "Necklaces"),
                            ("rings", "Rings"),
                            ("bangles", "Bangles"),
                            ("earrings", "Earrings"),
                            ("anklets", "Anklets"),
                            ("mangalsutras", "Mangalsutras"),
                            ("bracelets", "Bracelets"),
                            ("nose-pins", "Nose Pins"),
                            ("solitaires", "Solitaires"),
                            ("watch-jewelry", "Watch jewelry"),
                            ("kada", "Kada"),
                            ("mens-jewelry", "Men's jewelry"),
                            ("chains", "Chains"),
                            ("coins", "Coins"),
                            ("kids-jewelry", "Kids jewelry"),
                            ("wedding", "Wedding"),
                            ("gold", "Gold"),
                            ("diamond", "Diamond"),
                            ("dailywear", "Dailywear"),
                            ("traditional", "Traditional"),
                            ("modern", "Modern"),
                            ("mens", "Men's"),
                            ("kids", "Kids"),
                            ("custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("diamond", "Diamond"),
                            ("platinum", "Platinum"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
