# Generated by Django 5.2.3 on 2025-06-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="product",
            name="final_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="labour_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("gold", "Gold"),
                    ("diamond", "Diamond"),
                    ("silver", "Silver"),
                    ("platinum", "Platinum"),
                ],
                default="gold",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Enter weight in grams",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="approx_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="carat",
            field=models.IntegerField(
                default=22, help_text="Carat value (e.g., 18, 22)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="MetalRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("diamond", "Diamond"),
                            ("silver", "Silver"),
                            ("platinum", "Platinum"),
                        ],
                        max_length=10,
                    ),
                ),
                ("carat", models.IntegerField(help_text="Carat value (e.g., 18, 22)")),
                (
                    "tola_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter price per tola (11.66g)",
                        max_digits=10,
                    ),
                ),
                (
                    "rate_per_gram",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("type", "carat")},
            },
        ),
    ]
