# Generated by Django 5.2.3 on 2025-06-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0002_alter_product_options_product_final_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metalrate",
            name="tola_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Enter price per tola (11.66g) for gold, per carat for diamonds",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="metalrate",
            name="type",
            field=models.CharField(
                choices=[("gold", "Gold"), ("diamond", "Diamond")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="material",
            field=models.CharField(
                choices=[("gold", "Gold"), ("diamond", "Diamond")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("gold", "Gold"), ("diamond", "Diamond")],
                default="gold",
                max_length=10,
            ),
        ),
    ]
