# Generated by Django 5.2.3 on 2025-06-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0003_alter_metalrate_tola_price_alter_metalrate_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MetalRate",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
