# Generated by Django 5.2.3 on 2025-06-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0005_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Category Name"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Category Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Category Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Category Icon"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TargetAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Audience Name"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Audience Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Audience Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Audience Icon"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
            ],
            options={
                "verbose_name": "Target Audience",
                "verbose_name_plural": "Target Audiences",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Legacy single category field (deprecated)",
                max_length=50,
                verbose_name="Legacy Category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                help_text="Select one or more product categories",
                to="jewelry.productcategory",
                verbose_name="Product Categories",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="target_audiences",
            field=models.ManyToManyField(
                help_text="Select one or more target audiences",
                to="jewelry.targetaudience",
                verbose_name="Target Audiences",
            ),
        ),
    ]
