# Generated by Django 5.2.3 on 2025-06-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0006_productcategory_targetaudience_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="product",
            name="target_audiences",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("pendants", "Pendants"),
                    ("necklaces", "Necklaces"),
                    ("rings", "Rings"),
                    ("bangles", "Bangles"),
                    ("earrings", "Earrings"),
                    ("anklets", "Anklets"),
                    ("mangalsutra", "Mangalsutra"),
                    ("bracelets", "Bracelets"),
                    ("chains", "Chains"),
                    ("nose-pins", "Nose Pins"),
                    ("solitaires", "Solitaires"),
                    ("watch-jewelry", "Watch jewelry"),
                    ("kada", "Kada"),
                    ("mens", "Mens"),
                    ("women", "Women"),
                    ("kids", "Kids"),
                    ("couple", "Couple"),
                    ("engagement", "Engagement"),
                    ("marriage", "Marriage"),
                    ("daily-wear", "Daily Wear"),
                    ("party-wear", "Party Wear"),
                    ("traditional", "Traditional"),
                    ("modern", "Modern"),
                    ("luxury", "Luxury"),
                    ("budget", "Budget"),
                ],
                max_length=32,
                verbose_name="Product Category",
            ),
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
        migrations.DeleteModel(
            name="TargetAudience",
        ),
    ]
