# Generated by Django 5.2.3 on 2025-06-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0007_remove_product_categories_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MetalRate",
        ),
    ]
