# Generated by Django 5.2.3 on 2025-06-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0008_delete_metalrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("pendants", "Pendants"),
                            ("necklaces", "Necklaces"),
                            ("rings", "Rings"),
                            ("bangles", "Bangles"),
                            ("earrings", "Earrings"),
                            ("anklets", "Anklets"),
                            ("mangalsutra", "Mangalsutra"),
                            ("bracelets", "Bracelets"),
                            ("chains", "Chains"),
                            ("nose-pins", "Nose Pins"),
                            ("solitaires", "Solitaires"),
                            ("watch-jewelry", "Watch jewelry"),
                            ("kada", "Kada"),
                            ("mens", "Mens"),
                            ("women", "Women"),
                            ("kids", "Kids"),
                            ("couple", "Couple"),
                            ("engagement", "Engagement"),
                            ("marriage", "Marriage"),
                            ("daily-wear", "Daily Wear"),
                            ("party-wear", "Party Wear"),
                            ("traditional", "Traditional"),
                            ("modern", "Modern"),
                            ("luxury", "Luxury"),
                            ("budget", "Budget"),
                        ],
                        max_length=32,
                        unique=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=50, verbose_name="Display Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Category Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Category Icon"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
                "ordering": ["sort_order", "display_name"],
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                help_text="Select one or more categories for this product",
                to="jewelry.productcategory",
                verbose_name="Product Categories",
            ),
        ),
    ]
