# Generated by Django 5.2.3 on 2025-06-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0009_productcategory_remove_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="base_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="final_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="labour_charge",
        ),
    ]
