# Generated by Django 5.2.3 on 2025-06-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "jewelry",
            "0010_remove_product_base_price_remove_product_final_price_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="product",
            name="clarity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="total_ratings",
        ),
        migrations.DeleteModel(
            name="ProductRating",
        ),
    ]
