# Generated by Django 5.2.3 on 2025-06-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jewelry",
            "0011_remove_product_average_rating_remove_product_clarity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="metal_purity",
            field=models.CharField(
                help_text="e.g., 18K, 22K, 24K",
                max_length=10,
                verbose_name="Metal Purity",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="metal_type",
            field=models.CharField(
                choices=[
                    ("white_gold", "White Gold"),
                    ("yellow_gold", "Yellow Gold"),
                    ("rose_gold", "Rose Gold"),
                ],
                max_length=20,
                verbose_name="Metal Type",
            ),
        ),
    ]
