# Generated by Django 5.2.3 on 2025-06-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0013_alter_productcategory_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_bestseller",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_new_arrival",
        ),
    ]
