# Generated by Django 5.2.4 on 2025-07-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0017_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email_verification_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_email_verified",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="password_reset_expires",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="password_reset_token",
        ),
        migrations.DeleteModel(
            name="OTP",
        ),
    ]
