# Generated by Django 5.2.4 on 2025-07-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0018_remove_otp_and_email_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Discount Code"
                    ),
                ),
                ("percentage", models.IntegerField(verbose_name="Discount Percentage")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Discount Code",
                "verbose_name_plural": "Discount Codes",
                "ordering": ["-created_at"],
            },
        ),
    ]
