# Generated by Django 5.2.4 on 2025-07-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0019_discountcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.IntegerField(verbose_name="Discount Percentage")),
                ("is_used", models.BooleanField(default=False, verbose_name="Used")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
                (
                    "discount_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jewelry.discountcode",
                        verbose_name="Discount Code",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Discount",
                "verbose_name_plural": "User Discounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
