# Generated by Django 5.2.4 on 2025-07-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0021_diamondproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diamondproduct",
            name="shape",
            field=models.CharField(
                choices=[
                    ("round", "Round"),
                    ("oval", "Oval"),
                    ("princess", "Princess"),
                    ("cushion", "Cushion"),
                    ("emerald", "Emerald"),
                    ("marquise", "Marquise"),
                    ("pear", "Pear"),
                    ("heart", "Heart"),
                    ("asscher", "Asscher"),
                    ("radiant", "Radiant"),
                    ("trillion", "Trillion"),
                    ("baguette", "Baguette"),
                    ("rose_cut", "Rose Cut"),
                    ("old_mine_cut", "Old Mine Cut"),
                    ("old_european_cut", "Old European Cut"),
                    ("hexagon", "Hexagon"),
                    ("lozenge", "Lozenge"),
                    ("shield", "Shield"),
                    ("tapered_baguette", "Tapered Baguette"),
                    ("briolette", "Briolette"),
                ],
                max_length=30,
                verbose_name="Shape",
            ),
        ),
    ]
