# Generated by Django 5.2.4 on 2025-07-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0022_alter_diamondproduct_shape"),
    ]

    operations = [
        # Remove any AlterField operations for 'certification', 'certificate_number', 'clarity', and 'cut' in DiamondProduct.
    ]
