# Generated by Django 5.2.4 on 2025-07-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0025_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_hover",
            field=models.ImageField(
                blank=True,
                help_text="Second image to show on hover",
                null=True,
                upload_to="product_images/",
                verbose_name="Product Image (Hover)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total stone weight in grams",
                max_digits=8,
                verbose_name="Total Weight (grams)",
            ),
        ),
    ]
