# Generated by Django 5.2.4 on 2025-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0027_payment_completed_at_payment_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diamondproduct",
            name="shape",
            field=models.CharField(
                choices=[
                    ("round", "Round"),
                    ("oval", "Oval"),
                    ("princess", "Princess"),
                    ("cushion", "Cushion"),
                    ("emerald", "Emerald"),
                    ("marquise", "Marquise"),
                    ("pear", "Pear"),
                    ("heart", "Heart"),
                    ("asscher", "Asscher"),
                    ("radiant", "Radiant"),
                    ("trillion", "Trillion"),
                    ("baguette", "Baguette"),
                    ("rose_cut", "Rose Cut"),
                    ("old_mine_cut", "Old Mine Cut"),
                    ("old_european_cut", "Old European Cut"),
                    ("hexagon", "Hexagon"),
                    ("lozenge", "Lozenge"),
                    ("shield", "Shield"),
                    ("tapered_baguette", "Tapered Baguette"),
                    ("briolette", "Briolette"),
                    ("half_moon", "Half Moon"),
                ],
                max_length=30,
                verbose_name="Shape",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("pendants", "Pendants"),
                    ("necklaces", "Necklaces"),
                    ("rings", "Rings"),
                    ("bangles", "Bangles"),
                    ("earrings", "Earrings"),
                    ("mangalsutra", "Mangalsutra"),
                    ("bracelets", "Bracelets"),
                    ("chains", "Chains"),
                    ("nose-pins", "Nose Pins"),
                    ("solitaires", "Solitaires"),
                    ("watch-jewelry", "Watch jewelry"),
                    ("kada", "Kada"),
                    ("mens", "Mens"),
                    ("women", "Women"),
                    ("kids", "Kids"),
                    ("couple", "Couple"),
                    ("engagement", "Engagement"),
                    ("daily-wear", "Daily Wear"),
                    ("party-wear", "Party Wear"),
                    ("traditional", "Traditional"),
                    ("other", "Other"),
                ],
                max_length=32,
                unique=True,
                verbose_name="Category Name",
            ),
        ),
    ]
