# Generated by Django 5.2.4 on 2025-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0028_alter_diamondproduct_shape_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diamondproduct",
            name="shape",
            field=models.CharField(
                choices=[
                    ("round", "Round"),
                    ("oval", "Oval"),
                    ("princess", "Princess"),
                    ("cushion", "Cushion"),
                    ("emerald", "Emerald"),
                    ("marquise", "Marquise"),
                    ("pear", "Pear"),
                    ("heart", "Heart"),
                    ("asscher", "Asscher"),
                    ("radiant", "Radiant"),
                    ("trillion", "Trillion"),
                    ("baguette", "Baguette"),
                    ("hexagon", "Hexagon"),
                    ("lozenge", "Lozenge"),
                    ("shield", "Shield"),
                    ("tapered_baguette", "Tapered Baguette"),
                    ("briolette", "Briolette"),
                    ("half_moon", "Half Moon"),
                    ("square_caution", "Square Caution"),
                    ("coffin", "Coffin"),
                    ("square_radiant", "Square Radiant"),
                    ("bullet", "Bullet"),
                    ("trapezoid", "Trapezoid"),
                ],
                max_length=30,
                verbose_name="Shape",
            ),
        ),
    ]
