# Generated by Django 5.2.4 on 2025-07-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0029_alter_diamondproduct_shape"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diamondproduct",
            name="color",
            field=models.CharField(
                choices=[("D", "D"), ("E", "E"), ("F", "F"), ("G", "G"), ("H", "H")],
                max_length=2,
                verbose_name="Color Grade",
            ),
        ),
    ]
