# Generated by Django 5.2.4 on 2025-07-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0030_alter_diamondproduct_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="diamondproduct",
            name="origin",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Origin"
            ),
        ),
    ]
