# Generated by Django 5.2.4 on 2025-07-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0031_diamondproduct_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hover_video",
            field=models.FileField(
                blank=True,
                help_text="Video to play on hover (autoplay, muted, no controls)",
                null=True,
                upload_to="product_videos/",
                verbose_name="Product Hover Video",
            ),
        ),
    ]
