# Generated by Django 5.2.4 on 2025-08-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0033_remove_product_image_hover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("pendants", "Pendants"),
                    ("necklaces", "Necklaces"),
                    ("rings", "Rings"),
                    ("bangles", "Bangles"),
                    ("earrings", "Earrings"),
                    ("mangalsutra", "Mangalsutra"),
                    ("bracelets", "Bracelets"),
                    ("chains", "Chains"),
                    ("nose-pins", "Nose Pins"),
                    ("solitaires", "Solitaires"),
                    ("diamonds", "Diamonds"),
                    ("watch-jewelry", "Watch jewelry"),
                    ("kada", "Kada"),
                    ("mens", "Mens"),
                    ("women", "Women"),
                    ("kids", "Kids"),
                    ("couple", "Couple"),
                    ("engagement", "Engagement"),
                    ("daily-wear", "Daily Wear"),
                    ("party-wear", "Party Wear"),
                    ("traditional", "Traditional"),
                    ("other", "Other"),
                ],
                max_length=32,
                unique=True,
                verbose_name="Category Name",
            ),
        ),
    ]
