# Generated by Django 5.2.4 on 2025-08-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0033_remove_product_image_hover"),
    ]

    operations = [
        migrations.AddField(
            model_name="diamondproduct",
            name="clarity",
            field=models.CharField(
                choices=[
                    ("IF", "IF (Internally Flawless)"),
                    ("VVS1", "VVS1 (Very Very Slightly Included 1)"),
                    ("VVS2", "VVS2 (Very Very Slightly Included 2)"),
                    ("VS1", "VS1 (Very Slightly Included 1)"),
                    ("VS2", "VS2 (Very Slightly Included 2)"),
                    ("SI1", "SI1 (Slightly Included 1)"),
                ],
                max_length=10,
                null=True,
                verbose_name="Clarity Grade",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="diamond_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight of diamonds in carats",
                max_digits=5,
                null=True,
                verbose_name="Diamond Weight (Carat)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gold_clarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("very_good", "Very Good"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                ],
                max_length=20,
                null=True,
                verbose_name="Gold Clarity",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gold_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yellow", "Yellow Gold"),
                    ("white", "White Gold"),
                    ("rose", "Rose Gold"),
                    ("pink", "Pink Gold"),
                    ("green", "Green Gold"),
                ],
                max_length=20,
                null=True,
                verbose_name="Gold Color",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="net_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Net weight of the gold product in grams",
                max_digits=8,
                null=True,
                verbose_name="Net Weight (grams)",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("pendants", "Pendants"),
                    ("necklaces", "Necklaces"),
                    ("rings", "Rings"),
                    ("bangles", "Bangles"),
                    ("earrings", "Earrings"),
                    ("mangalsutra", "Mangalsutra"),
                    ("bracelets", "Bracelets"),
                    ("chains", "Chains"),
                    ("nose-pins", "Nose Pins"),
                    ("solitaires", "Solitaires"),
                    ("diamonds", "Diamonds"),
                    ("watch-jewelry", "Watch jewelry"),
                    ("kada", "Kada"),
                    ("mens", "Mens"),
                    ("women", "Women"),
                    ("kids", "Kids"),
                    ("couple", "Couple"),
                    ("engagement", "Engagement"),
                    ("daily-wear", "Daily Wear"),
                    ("party-wear", "Party Wear"),
                    ("traditional", "Traditional"),
                    ("other", "Other"),
                ],
                max_length=32,
                unique=True,
                verbose_name="Category Name",
            ),
        ),
    ]
