# Generated by Django 5.2.4 on 2025-08-14 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0035_alter_diamondproduct_clarity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gold_clarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("9k", "9K"),
                    ("10k", "10K"),
                    ("14k", "14K"),
                    ("18k", "18K"),
                    ("22k", "22K"),
                ],
                max_length=20,
                null=True,
                verbose_name="Gold Karat",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. 10 digits allowed.",
                        regex="^\\+?1?\\d{9,13}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
    ]
