# Generated by Django 5.2.4 on 2025-08-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0036_alter_product_gold_clarity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="has_diamond",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_emerald",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_other_gemstone",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_pearl",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_ruby",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_sapphire",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_topaz",
        ),
        migrations.RemoveField(
            model_name="product",
            name="other_gemstone_name",
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total gold weight in grams",
                max_digits=8,
                verbose_name="Total Weight (grams)",
            ),
        ),
    ]
