# Generated by Django 5.2.4 on 2025-08-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0037_remove_product_has_diamond_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="gold_color",
        ),
    ]
