# Generated by Django 5.2.4 on 2025-08-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0038_remove_product_gold_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="diamondproduct",
            name="certification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("certified_gia", "Certified GIA"),
                    ("certified_igi", "Certified IGI"),
                    ("loose", "Loose"),
                ],
                max_length=20,
                null=True,
                verbose_name="Certification",
            ),
        ),
        migrations.AddField(
            model_name="diamondproduct",
            name="cut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ideal", "Ideal"),
                    ("excellent", "Excellent"),
                    ("very_good", "Very Good"),
                ],
                max_length=20,
                null=True,
                verbose_name="Cut",
            ),
        ),
        migrations.AlterField(
            model_name="diamondproduct",
            name="clarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FL", "FL (Flawless)"),
                    ("IF", "IF (Internally Flawless)"),
                    ("VVS1", "VVS1 (Very Very Slightly Included 1)"),
                    ("VVS2", "VVS2 (Very Very Slightly Included 2)"),
                    ("VS1", "VS1 (Very Slightly Included 1)"),
                    ("VS2", "VS2 (Very Slightly Included 2)"),
                    ("SI1", "SI1 (Slightly Included 1)"),
                    ("SI2", "SI2 (Slightly Included 2)"),
                    ("SI3", "SI3 (Slightly Included 3)"),
                    ("VVS", "VVS (Very Very Slightly Included)"),
                    ("VS", "VS (Very Slightly Included)"),
                    ("SI", "SI (Slightly Included)"),
                    ("IGI", "IGI"),
                    ("GIA", "GIA"),
                    ("VVS-VS", "VVS-VS"),
                    ("VS-SI", "VS-SI"),
                ],
                max_length=10,
                null=True,
                verbose_name="Clarity Grade",
            ),
        ),
    ]
