# Generated by Django 5.2.4 on 2025-08-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0039_diamondproduct_certification_diamondproduct_cut_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diamondproduct",
            name="certification",
            field=models.CharField(
                blank=True,
                choices=[("GIA", "GIA"), ("IGI", "IGI"), ("loose", "Loose")],
                max_length=20,
                null=True,
                verbose_name="Certification",
            ),
        ),
        migrations.AlterField(
            model_name="diamondproduct",
            name="color",
            field=models.CharField(
                choices=[
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("PINK", "PINK"),
                    ("YELLOW", "YELLOW"),
                    ("BLUE", "BLUE"),
                    ("GREEN", "GREEN"),
                ],
                max_length=10,
                verbose_name="Color Grade",
            ),
        ),
        migrations.AlterField(
            model_name="diamondproduct",
            name="shape",
            field=models.CharField(
                choices=[
                    ("antique", "Antique"),
                    ("round", "Round"),
                    ("oval", "Oval"),
                    ("princess", "Princess"),
                    ("cushion", "Cushion"),
                    ("emerald", "Emerald"),
                    ("marquise", "Marquise"),
                    ("pear", "Pear"),
                    ("heart", "Heart"),
                    ("asscher", "Asscher"),
                    ("radiant", "Radiant"),
                    ("trillion", "Trillion"),
                    ("baguette", "Baguette"),
                    ("hexagon", "Hexagon"),
                    ("lozenge", "Lozenge"),
                    ("shield", "Shield"),
                    ("tapered_baguette", "Tapered Baguette"),
                    ("briolette", "Briolette"),
                    ("half_moon", "Half Moon"),
                    ("square_caution", "Square Caution"),
                    ("coffin", "Coffin"),
                    ("square_radiant", "Square Radiant"),
                    ("bullet", "Bullet"),
                    ("trapezoid", "Trapezoid"),
                ],
                max_length=30,
                verbose_name="Shape",
            ),
        ),
    ]
