# Generated by Django 5.2.4 on 2025-08-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0042_alter_productcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diamondproduct",
            name="clarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FL", "FL (Flawless)"),
                    ("IF", "IF (Internally Flawless)"),
                    ("VVS1", "VVS1 (Very Very Slightly Included 1)"),
                    ("VVS2", "VVS2 (Very Very Slightly Included 2)"),
                    ("VS1", "VS1 (Very Slightly Included 1)"),
                    ("VS2", "VS2 (Very Slightly Included 2)"),
                    ("SI1", "SI1 (Slightly Included 1)"),
                    ("SI2", "SI2 (Slightly Included 2)"),
                    ("SI3", "SI3 (Slightly Included 3)"),
                    ("VVS", "VVS (Very Very Slightly Included)"),
                    ("VS", "VS (Very Slightly Included)"),
                    ("SI", "SI (Slightly Included)"),
                    ("IGI", "IGI"),
                    ("GIA", "GIA"),
                    ("VVS-VS", "VVS-VS"),
                    ("VS-SI", "VS-SI"),
                ],
                max_length=20,
                null=True,
                verbose_name="Clarity Grade",
            ),
        ),
        migrations.AlterField(
            model_name="diamondproduct",
            name="color",
            field=models.CharField(
                choices=[
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("PINK", "PINK"),
                    ("YELLOW", "YELLOW"),
                    ("BLUE", "BLUE"),
                    ("GREEN", "GREEN"),
                    ("PURPLE", "PURPLE"),
                    ("BLACK", "BLACK"),
                    ("RED", "RED"),
                ],
                max_length=10,
                verbose_name="Color Grade",
            ),
        ),
    ]
