# Generated by Django 5.2.4 on 2025-08-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0034_alter_productcategory_name"),
        ("jewelry", "0043_alter_diamondproduct_clarity_and_more"),
    ]

    operations = []
