# Generated by Django 5.2.4 on 2025-08-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jewelry", "0044_merge_20250816_0842"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Category Name"
            ),
        ),
    ]
